displayName=Tangle Dink Plugin
author=ZH-Systems
build=standard
description=Player sync, collection log, and clan webhook plugin
tags=sync,clan,webhook,collection,sidebar
plugins=tccrewplugin.TangleDinkPlugin
version=1.14.0
