displayName=Tangle Crew Plugin
author=ZacharyHeil
build=standard
description=Clan Event focused Plugin, based on a Fork of the DINK plugin
tags=bingo,clan,loot,logger,collection,pet,death,xp,level,notifications,discord,speedrun,diary,combat achievements,combat task,barbarian assault,high level gambles
plugins=tccrewplugin.TcCrewPlugin
version=1.14.0
