displayName=Tangle Crew Plugin
author=ZH-Systems
build=standard
description=Clan Event focused Plugin with clan chat webhooks, based on a fork of the DINK plugin
tags=bingo,clan,loot,logger,collection,pet,death,xp,level,notifications,discord,speedrun,diary,combat achievements,combat task,barbarian assault,high level gambles,webhook
plugins=tccrewplugin.TcCrewPlugin
version=1.14.0
